require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  Exclude:
    - 'db/schema.rb'
    - 'bundle/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
    -  Gemfile
    - 'bin/**/*'
    - 'db/migrate/*'
    - 'config/**/*'

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/routes.rb'

Lint/MissingSuper:
  Enabled: false